services:

  postgres:
    image: postgres:15
    container_name: motor-postgres
    restart: always
    environment:
      POSTGRES_DB: motor_recomendaciones_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sandia4you 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - motor_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: motor-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - motor_network

volumes:
  postgres_data:

networks:
  motor_network:
